services:
  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: postgres_container_test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

 
volumes:
  postgres_data:
